name: Node CI

on:
  pull_request:
    branches: [main]

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
    - uses: actions/checkout@v2
    - uses: actions/setup-node@v2
      with:
        node-version: "16"
        cache: "yarn"

    - run: yarn install --frozen-lockfile
    - run: yarn run build
    - run: yarn run test
    - run: yarn run test:coverage
